name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      if: contains(github.repository, 'NiklasMerz/cordova-plugin-fingerprint-aio')
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
